# Generated by Django 5.1.5 on 2025-01-16 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetorAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=20, verbose_name='setor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setor',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Ativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=250, verbose_name='nome do ativo')),
                ('ticket', models.CharField(max_length=10)),
                ('classe', models.CharField(max_length=10)),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('setor', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ativo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['ativo'],
            },
        ),
        migrations.CreateModel(
            name='MetaAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('qtd_fii', models.IntegerField(verbose_name='quantidade de fii')),
                ('qtd_acoes', models.IntegerField(verbose_name='quantidade de ações')),
                ('total', models.IntegerField(verbose_name='total de ativos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_meta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Meta',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=10)),
                ('classe', models.CharField(max_length=10)),
                ('tipo_operacao', models.CharField(max_length=20, verbose_name='tipo de operação')),
                ('data_operacao', models.DateTimeField(verbose_name='data da operação')),
                ('qtd', models.IntegerField(verbose_name='quantidade')),
                ('valor_cota', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='valor da cota')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='total da compra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_operacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operação',
                'verbose_name_plural': 'Operação',
                'ordering': ['-data_operacao'],
            },
        ),
        migrations.CreateModel(
            name='Proventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=10)),
                ('classe', models.CharField(max_length=10)),
                ('tipo_provento', models.CharField(max_length=20, verbose_name='tipo de provento')),
                ('valor_recebido', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='valor recebido')),
                ('data_pgto', models.DateTimeField(verbose_name='data do pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_provento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proventos',
                'verbose_name_plural': 'Proventos',
                'ordering': ['-data_pgto'],
            },
        ),
    ]
