# Generated by Django 5.1.5 on 2025-01-18 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0002_alter_ativos_fk_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='classe',
            field=models.CharField(choices=[('Ação', 'Ação'), ('FII', 'FII')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ativos',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteira.setorativo'),
        ),
    ]
