# Generated by Django 5.1.5 on 2025-01-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0003_alter_ativos_classe_alter_ativos_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='classe',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ativos',
            name='setor',
            field=models.CharField(max_length=50),
        ),
    ]
