# Generated by Django 5.1.5 on 2025-01-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0005_alter_ativos_fk_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativos',
            name='dividendos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='ativos',
            name='investimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='ativos',
            name='qtdAtivo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qtd'),
        ),
    ]
