# Generated by Django 5.1.5 on 2025-01-18 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0006_ativos_dividendos_ativos_investimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setor_ativo', to='carteira.setorativo', verbose_name='Setor'),
        ),
    ]
