# Generated by Django 5.1.5 on 2025-01-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0007_alter_ativos_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='setorativo',
            name='setor_classe',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='classe'),
        ),
    ]
