# Generated by Django 5.1.5 on 2025-01-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0008_setorativo_setor_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='ano',
            field=models.IntegerField(blank=True, null=True, verbose_name='ano'),
        ),
        migrations.AddField(
            model_name='proventos',
            name='ano',
            field=models.IntegerField(blank=True, null=True, verbose_name='ano'),
        ),
        migrations.AddField(
            model_name='proventos',
            name='mes',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='mês'),
        ),
    ]
