# Generated by Django 5.1.5 on 2025-01-20 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0011_alter_operacao_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='proventos',
            name='id_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='carteira.ativos'),
        ),
    ]
