# Generated by Django 5.1.5 on 2025-01-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0014_remove_operacao_ticket_alter_operacao_id_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='fonte_recurso',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fonte de recurso'),
        ),
    ]
