# Generated by Django 5.1.5 on 2025-01-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0015_operacao_fonte_recurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proventos',
            name='ticket',
        ),
        migrations.AlterField(
            model_name='operacao',
            name='tipo_operacao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='tipo de operação'),
        ),
    ]
