# Generated by Django 5.1.5 on 2025-01-26 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0019_remove_metaativo_status_anual_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecoTeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=10)),
                ('rentabilidade', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Rentabilidade')),
                ('ipca', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='IPCA+')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_preco_teto', to=settings.AUTH_USER_MODEL)),
                ('id_ativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='carteira.ativos', verbose_name='Ativos')),
            ],
            options={
                'verbose_name': 'Preço teto',
                'verbose_name_plural': 'Preço teto',
            },
        ),
    ]
