# Generated by Django 5.1.5 on 2025-01-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0020_precoteto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precoteto',
            name='classe',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='precoteto',
            name='rentabilidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Rentabilidade'),
        ),
    ]
