# Generated by Django 5.1.5 on 2025-01-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0021_alter_precoteto_classe_alter_precoteto_rentabilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precoteto',
            name='ipca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='IPCA+'),
        ),
    ]
