# Generated by Django 5.1.5 on 2025-01-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0022_alter_precoteto_ipca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaativo',
            name='classe',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='classe',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='precoteto',
            name='classe',
            field=models.CharField(default='', max_length=10),
        ),
    ]
