# Generated by Django 5.1.5 on 2025-01-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0023_alter_metaativo_classe_alter_operacao_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precoteto',
            name='rentabilidade',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=20, verbose_name='Rentabilidade'),
        ),
    ]
