# Generated by Django 5.1.5 on 2025-02-02 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0024_alter_precoteto_rentabilidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(default='', max_length=10)),
                ('qtd', models.IntegerField(verbose_name='Quantidade')),
                ('ano', models.IntegerField(blank=True, null=True, verbose_name='Ano')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_meta_ativo', to=settings.AUTH_USER_MODEL)),
                ('id_ativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='carteira.ativos', verbose_name='Ativos')),
            ],
            options={
                'verbose_name': 'Planejamento das metas',
                'verbose_name_plural': 'Planejamento das metas',
            },
        ),
    ]
