# Generated by Django 5.1.5 on 2025-02-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0025_planmetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmetas',
            name='qtd',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
    ]
