# Generated by Django 5.1.5 on 2025-02-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0026_alter_planmetas_qtd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmetas',
            name='qtd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade'),
        ),
    ]
