# Generated by Django 5.1.5 on 2025-02-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0027_alter_planmetas_qtd'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmetas',
            name='prov_cota',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='proventos'),
        ),
        migrations.AddField(
            model_name='planmetas',
            name='qtd_calc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
