# Generated by Django 5.1.5 on 2025-02-15 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0028_planmetas_prov_cota_planmetas_qtd_calc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMetasCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(default='', max_length=10)),
                ('valor_investido', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_meta_plan_calc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
