# Generated by Django 5.1.5 on 2025-03-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0029_planmetascalc'),
    ]

    operations = [
        migrations.AddField(
            model_name='proventos',
            name='status',
            field=models.CharField(default='A PAGAR', max_length=10),
        ),
    ]
