# Generated by Django 5.1.5 on 2025-03-12 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0030_proventos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor_ativo', to='carteira.setorativo', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='id_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carteira.ativos', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='planmetas',
            name='id_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carteira.ativos', verbose_name='Ativos'),
        ),
        migrations.AlterField(
            model_name='precoteto',
            name='id_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carteira.ativos', verbose_name='Ativos'),
        ),
        migrations.AlterField(
            model_name='proventos',
            name='id_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carteira.ativos', verbose_name='Ativos'),
        ),
    ]
