# Generated by Django 5.1.5 on 2025-04-05 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0031_alter_ativos_setor_alter_operacao_id_ativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaativo',
            name='meta_anual',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Meta Anual'),
        ),
        migrations.AlterField(
            model_name='metaativo',
            name='meta_geral',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Meta geral'),
        ),
        migrations.AlterField(
            model_name='metaativo',
            name='meta_geral_alcancada',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Meta geral alcançada'),
        ),
        migrations.CreateModel(
            name='Corretora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_corretora', models.CharField(max_length=255)),
                ('apelido', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_corretora', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rentabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentabilidade', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('ano', models.IntegerField(blank=True, null=True, verbose_name='ano')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rentabilidade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
