# Generated by Django 5.1.5 on 2025-04-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0032_alter_metaativo_meta_anual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativos',
            name='corretora',
            field=models.CharField(default='', max_length=255),
        ),
    ]
