# Generated by Django 5.1.5 on 2025-04-10 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0034_rentabilidade_id_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='corretora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativos_corretora', to='carteira.corretora', verbose_name='Corretora'),
        ),
    ]
