# Generated by Django 5.1.5 on 2025-04-11 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0035_alter_ativos_corretora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='corretora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ativos_corretora', to='carteira.corretora', verbose_name='Corretora'),
        ),
    ]
