# Generated by Django 5.1.5 on 2025-04-12 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0038_remove_setorativo_fk_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='setorativo',
            name='fk_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_setor', to=settings.AUTH_USER_MODEL),
        ),
    ]
