# Generated by Django 5.1.5 on 2025-04-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0039_setorativo_fk_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='setor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
