# Generated by Django 5.1.5 on 2025-04-12 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0040_alter_ativos_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='setor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='setor_ativo', to='carteira.setorativo', verbose_name='Setor'),
        ),
    ]
