# Generated by Django 5.1.5 on 2025-04-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0041_alter_ativos_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='mes',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='mês'),
        ),
    ]
