# Generated by Django 5.1.5 on 2025-05-17 01:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0042_operacao_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='setor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_ativo', to='carteira.setorativo', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='metaativo',
            name='meta_alcancada',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meta anual alcançada'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='id_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carteira.ativos', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total da Operação'),
        ),
        migrations.AlterField(
            model_name='planmetas',
            name='id_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carteira.ativos', verbose_name='Ativos'),
        ),
        migrations.AlterField(
            model_name='precoteto',
            name='id_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carteira.ativos', verbose_name='Ativos'),
        ),
        migrations.AlterField(
            model_name='precoteto',
            name='rentabilidade',
            field=models.DecimalField(decimal_places=2, default=Decimal('6.00'), max_digits=20, verbose_name='Rentabilidade desejada'),
        ),
        migrations.AlterField(
            model_name='proventos',
            name='id_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carteira.ativos', verbose_name='Ativos'),
        ),
        migrations.AlterField(
            model_name='rentabilidade',
            name='id_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carteira.ativos', verbose_name='Ativo'),
        ),
    ]
