# Generated by Django 5.1.5 on 2025-05-17 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0043_alter_ativos_setor_alter_metaativo_meta_alcancada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaativo',
            name='meta_alcancada',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meta anual alçancada'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='id_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carteira.ativos', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total da Operaçao'),
        ),
        migrations.AlterField(
            model_name='planmetas',
            name='id_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carteira.ativos', verbose_name='Ativos'),
        ),
        migrations.AlterField(
            model_name='precoteto',
            name='id_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carteira.ativos', verbose_name='Ativos'),
        ),
        migrations.AlterField(
            model_name='proventos',
            name='id_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carteira.ativos', verbose_name='Ativos'),
        ),
        migrations.AlterField(
            model_name='rentabilidade',
            name='id_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carteira.ativos', verbose_name='Ativo'),
        ),
    ]
