# Generated by Django 5.1.5 on 2025-05-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0044_alter_metaativo_meta_alcancada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proventos',
            name='valor_recebido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='valor recebido'),
        ),
    ]
