# Generated by Django 5.1.5 on 2025-05-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0045_alter_proventos_valor_recebido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='valor_cota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='valor da cota'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Total da Operaçao'),
        ),
    ]
